### ISSUE TITLE
Hide functions

### ISSUE THREAD

**Issue by martinguerrero89** [harpomaxx/galgo#14]
Undocumented code objects:
    'ArrayTest' 'ArrayTrain' 'alloc2' 'asMut' 'base_end_gen_callback'
    'base_report_callback' 'base_save_pop_callback'
    'base_save_pop_final_callback' 'base_save_pop_partial_callback'
    'base_start_gen_callback' 'cDist' 'cluster_algorithm' 'createFolds'
    'crossvalidation' 'default_callback' 'hmean' 'kcrossover' 'minGenes'
    'no_report_callback' 'offspring' 'pen' 'reord' 'subDist' 'ucrossover'
  All user-level objects in a package should have documentation entries.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.

**Comment by harpomaxx** [comment]
remove @export from these functions.
