### ISSUE TITLE
Check dependencies

### ISSUE THREAD

**Issue by martinguerrero89** [harpomaxx/galgo#15]
'::' or ':::' import not declared from: 'methods'
  'library' or 'require' calls not declared from:
    'cluster' 'survcomp'
  'library' or 'require' calls in package code:
    'cluster' 'survcomp'
    Please use :: or requireNamespace() instead.
    See section 'Suggested packages' in the 'Writing R Extensions' manual.
  Unexported object imported by a ':::' call: 'survival:::survmean'
    See the note in ?`:::` about the use of this operator.
    Including base/recommended package(s):
    'survival'

**Comment by harpomaxx** [comment]
we replaced the survival::survmean function with a local version called RMST()
