### ISSUE TITLE
ERROR with galgo function

### ISSUE THREAD

**Issue by martinguerrero89** [harpomaxx/galgo#16]
galgoR::galgo(generations = 10,population = 20, prob_matrix = TCGA_expr, OS = OS)
  Error in .check_ncores(length(names)) : 7 simultaneous processes spawned
  Calls: <Anonymous> -> <Anonymous> -> makePSOCKcluster -> .check_ncores
  Execution halted

**Comment by harpomaxx** [comment]
fixed in commit 
https://github.com/harpomaxx/galgo/commit/3cc91da8397f3f8e8aca3618ad34232c4d5803fe
