### ISSUE TITLE
error in luad_data.rds download corrupted file?

### ISSUE THREAD

**Issue by martinguerrero89** [harpomaxx/galgo#17]
utils::download.file("https://bit.ly/luad_data_galgo",dest_file) download a corrupted file.
the readRDS function throw and error:
```
Error in readRDS(dest_file) : error reading from connection
In addition: Warning message:
In readRDS(dest_file) : invalid or incomplete compressed data
```

If download manually with the link, the files download correctly. 
Windows issue? This did not happen before

Downloaded by  utils::download.file("https://bit.ly/luad_data_galgo",dest_file):
SHA1 hash de C:\Users\Usuario\Documents\luad_data.rds:
16d705d782a8245dd098813bc9e93f4bbc1713a5

Downloaded using the link (this file is the one working)
SHA1 hash de C:\Users\Usuario\Downloads\luad_data.rds:
d6147eaff7dfffd04c1d05e5d87abd33dc385c04

**Comment by harpomaxx** [comment]
fixed with commit https://github.com/harpomaxx/galgo/commit/23968372b86b4aff06d01e3b8da1555750fd143e
