### ISSUE TITLE
subset() function from cba package is experimental

### ISSUE THREAD

**Issue by harpomaxx** [harpomaxx/galgo#20]
The subset function using for calculating subset matrix distance is tagged as experimental in the cba package and should be replaced any time soon.

**Comment by martinguerrero89** [comment]
(Own reminder): Try
https://rdrr.io/cran/usedist/man/dist_subset.html

**Comment by martinguerrero89** [comment]
Finally, the package 'proxy' was needed to subset the distance matrices with a custom made function.
We are no using cba or usedist packages.
8a994984de0b429ffc62ccd07aa02c5e1077b25a
