### ISSUE TITLE
examples execution takes more than 10s 

### ISSUE THREAD

**Issue by harpomaxx** [harpomaxx/galgo#25]
Most of current examples take more than 10s. The problem was solved by enclosing time-consuming examples inside \dontrun. However, the vignette still takes some time mostly because of the changes implemented in the use_rna_luad() function in commit aaedf62807c9cd53e777fc6ed2e697e5c3875170 and issue #22. Perhaps we should do the same for the vignette??

**Comment by harpomaxx** [comment]
a different approach consists of having a small version of rna_luad included in the package and adds to the use_rna_luad() function a new parameter for obtaining the full version of the dataset.
```
rna_luad <- use_rna_luad() #small version of the data (default)
rna_luad_full <- use_rna_luad( full_dataset = TRUE ) #full version of the data(optional)
```

**Comment by martinguerrero89** [comment]
I think its a good idea, but I doubt any example of Galgo would take less than 10s... Also, the full dataset is needed for performing Wilkerson classification, so for those examples this approach would not work
