### ISSUE TITLE
a suggestion for changing the description file

### ISSUE THREAD

**Issue by harpomaxx** [harpomaxx/galgo#27]
Remove the **Algorithm** word from the description file and replace it with **Framework** instead.

_An Evolutionary Framework for the Identification and Study of Prognostic Gene Expression Signatures in Cancer._

I believe that way is more general and perhaps gives the idea of it can be used in several studies.

**Comment by martinguerrero89** [comment]
Done
commit 60bf7996ab36f7b2319c97d7a9703b8b529106cb
